[Backport MR-10814] OpenXRRemoting: Support building against Holographic.Remoting.OpenXr >= 2.9.3
Starting with Microsoft.Holographic.Remoting.OpenXr 2.9.3, the struct
`XrRemotingPreferredGraphicsAdapterMSFT` is defined in `openxr_msft_holographic_remoting.h`
and it requires the type LUID to be defined.

Since LUID is defined in `windows.h` (see `OpenXR-SDK-Source/specification/registry/xr.xml`),
we include the corresponding VTK header and fixes the following error reported
when building the vtkRenderingOpenXRRemoting module:

```
C:\path\to\\OpenXRRemoting-install\build\native\include\openxr\openxr_msft_holographic_remoting.h(405,14): error
C3646: 'adapterLuid': unknown override specifier
```

Merge-request: vtk/vtk!10814