[Slicer] Fix compilation error in vtkOpenXRManagerRemoteConnection.cxx
This fixes the following error with Visual Studio 2022 (MSVC 14.44.35207 toolset) with Cxx standard set to C++17:

  vtkOpenXRManagerRemoteConnection.cxx
C:\D\S4R\VTK\Rendering\OpenXRRemoting\vtkOpenXRManagerRemoteConnection.cxx(129,24): error C2039: 'chrono_literals': is not a member of 'std' [C:\D\SlicerVirtualReality-win64rel\vtkRenderingOpenXRRemoting-build\vtkRenderingOpenXRRemoting\RenderingOpenXRRemoting.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\thread(37,1):
      see declaration of 'std'
C:\D\S4R\VTK\Rendering\OpenXRRemoting\vtkOpenXRManagerRemoteConnection.cxx(129,24): error C2871: 'chrono_literals': a namespace with this name does not exist [C:\D\SlicerVirtualReality-win64rel\vtkRenderingOpenXRRemoting-build\vtkRenderingOpenXRRemoting\RenderingOpenXRRemoting.vcxproj]
C:\D\S4R\VTK\Rendering\OpenXRRemoting\vtkOpenXRManagerRemoteConnection.cxx(130,31): error C3688: invalid literal suffix 'ms'; literal operator or literal operator template 'operator ""ms' not found [C:\D\SlicerVirtualReality-win64rel\vtkRenderingOpenXRRemoting-build\vtkRenderingOpenXRRemoting\RenderingOpenXRRemoting.vcxproj]
C:\D\S4R\VTK\Rendering\OpenXRRemoting\vtkOpenXRManagerRemoteConnection.cxx(130,21): error C2672: 'std::this_thread::sleep_for': no matching overloaded function found [C:\D\SlicerVirtualReality-win64rel\vtkRenderingOpenXRRemoting-build\vtkRenderingOpenXRRemoting\RenderingOpenXRRemoting.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\thread(222,10):
      could be 'void std::this_thread::sleep_for(const std::chrono::duration<_Rep,_Period> &)'

The problem is that chrono literals are available in various namespaces (std::literals::chrono_literals or std::chrono_literals)
depending on compiler and C++ standard version.

Fixed by simply using std::chrono::milliseconds, which is just as readable as the chrono literals and it works across many compiler versions and settings.

The change is currently under review in VTK gitlab:
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/12838